version: "3"

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - database
    environment:
      - DB_USER=root
      - DB_PASSWORD=12345
      - DB_HOST=database
      - DB_PORT=3306
      - DB_NAME=task-management-db

  frontend:
    build: ./frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend

  database:
    image: "mysql:latest"
    environment:
      - MYSQL_ROOT_PASSWORD=12345
      - MYSQL_DATABASE=task-management-db
    ports:
      - "3306:3306"
