version: "3"

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - database

  frontend:
    build: ./frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend

  database:
    image: "postgres:latest" # Use an appropriate database image
    environment:
      POSTGRES_DB: your_database_name
      POSTGRES_USER: your_database_user
      POSTGRES_PASSWORD: your_database_password
